# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Jekymail
long-title: Jekymail- HTML Emails Built with Jekyll 
email: mpope@somethingkiller.com
description: "Jekymail is a Jekyll Based Static Site Generator Tweaked for HTML Emails"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
timezone: America/New_York
year: 2021
sitemap: true

# Social networks
social-username:
  twitter: "@somethingkillr"
  linkedin: "michael-pope-6293795a"
  github: "nbkkb7x"
  instagram: "somethingkiller"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-purgecss

css_dir: "assets/css" # defaults to "css"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - _emails
  - _redirects

exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - purgecss.config.js
  - package.json

# Structure
navigation:
  - title: About
    url: /about
  - title: Contact
    url: /contact


permalink: /:title/

# Configure site collections
collections:
  emails:
    output: true
    permalink: /emails/:path/

defaults:
  - scope:
      path: ""
      type: "emails"
    values:
      layout: "emails"
